package com.doctorwork.sword.gateway.dal.model;

import java.io.Serializable;
import java.util.Date;

/**
 * This class corresponds to the database table <tt>discover_registry_config</tt>
 * 
 * This file is generated by <tt>dwframe<tt>
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may be
 * OVERWRITTEN by someone else. To modify the file, you should go to find the file
 * <tt>{project-home}/dalgen/mybatis_generator.xml<tt>. Modify the configuration file
 * according to your needs, then run <tt>ant</tt> to generate this file in {project-home}/dalgen.
 * 
 * @author dwframe
 * @since 2019-07-11
 */
public class DiscoverRegistryConfig implements Serializable {
    /**
     * <pre>
     * 
     * This field corresponds to the database column <tt>discover_registry_config.id<tt>
     * </pre>
     */
    private Long id;

    /**
     * <pre>
     * 注册中心标识
     * This field corresponds to the database column <tt>discover_registry_config.dscr_registry_id<tt>
     * </pre>
     */
    private String dscrRegistryId;

    /**
     * <pre>
     * 注册中心类型
     * This field corresponds to the database column <tt>discover_registry_config.dscr_registry_type<tt>
     * </pre>
     */
    private String dscrRegistryType;

    /**
     * <pre>
     * 注册中心配置
     * This field corresponds to the database column <tt>discover_registry_config.dscr_registry_config<tt>
     * </pre>
     */
    private String dscrRegistryConfig;

    /**
     * <pre>
     * 是否删除，0-未删除，1-删除，默认为0
     * This field corresponds to the database column <tt>discover_registry_config.is_delete<tt>
     * </pre>
     */
    private Integer isDelete;

    /**
     * <pre>
     * Create time, common column by DB rules
     * This field corresponds to the database column <tt>discover_registry_config.gmt_create<tt>
     * </pre>
     */
    private Date gmtCreate;

    /**
     * <pre>
     * Modified time,common column by DB rules 
     * This field corresponds to the database column <tt>discover_registry_config.gmt_modified<tt>
     * </pre>
     */
    private Date gmtModified;

    /** serialVersionUID */
    private static final long serialVersionUID = 1L;

    /**
     * <pre>
     * This field corresponds to the database column <tt>discover_registry_config.id<tt>
     * </pre>
     *
     * @return 
     */
    public Long getId() {
        return id;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>discover_registry_config.id<tt>
     * </pre>
     *
     * @param id 
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>discover_registry_config.dscr_registry_id<tt>
     * </pre>
     *
     * @return 注册中心标识
     */
    public String getDscrRegistryId() {
        return dscrRegistryId;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>discover_registry_config.dscr_registry_id<tt>
     * </pre>
     *
     * @param dscrRegistryId 注册中心标识
     */
    public void setDscrRegistryId(String dscrRegistryId) {
        this.dscrRegistryId = dscrRegistryId == null ? null : dscrRegistryId.trim();
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>discover_registry_config.dscr_registry_type<tt>
     * </pre>
     *
     * @return 注册中心类型
     */
    public String getDscrRegistryType() {
        return dscrRegistryType;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>discover_registry_config.dscr_registry_type<tt>
     * </pre>
     *
     * @param dscrRegistryType 注册中心类型
     */
    public void setDscrRegistryType(String dscrRegistryType) {
        this.dscrRegistryType = dscrRegistryType == null ? null : dscrRegistryType.trim();
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>discover_registry_config.dscr_registry_config<tt>
     * </pre>
     *
     * @return 注册中心配置
     */
    public String getDscrRegistryConfig() {
        return dscrRegistryConfig;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>discover_registry_config.dscr_registry_config<tt>
     * </pre>
     *
     * @param dscrRegistryConfig 注册中心配置
     */
    public void setDscrRegistryConfig(String dscrRegistryConfig) {
        this.dscrRegistryConfig = dscrRegistryConfig == null ? null : dscrRegistryConfig.trim();
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>discover_registry_config.is_delete<tt>
     * </pre>
     *
     * @return 是否删除，0-未删除，1-删除，默认为0
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>discover_registry_config.is_delete<tt>
     * </pre>
     *
     * @param isDelete 是否删除，0-未删除，1-删除，默认为0
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>discover_registry_config.gmt_create<tt>
     * </pre>
     *
     * @return Create time, common column by DB rules
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>discover_registry_config.gmt_create<tt>
     * </pre>
     *
     * @param gmtCreate Create time, common column by DB rules
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>discover_registry_config.gmt_modified<tt>
     * </pre>
     *
     * @return Modified time,common column by DB rules 
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>discover_registry_config.gmt_modified<tt>
     * </pre>
     *
     * @param gmtModified Modified time,common column by DB rules 
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", dscrRegistryId=").append(dscrRegistryId);
        sb.append(", dscrRegistryType=").append(dscrRegistryType);
        sb.append(", dscrRegistryConfig=").append(dscrRegistryConfig);
        sb.append(", isDelete=").append(isDelete);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append("]");
        return sb.toString();
    }

    /**
     *
     * @param that
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DiscoverRegistryConfig other = (DiscoverRegistryConfig) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getDscrRegistryId() == null ? other.getDscrRegistryId() == null : this.getDscrRegistryId().equals(other.getDscrRegistryId()))
            && (this.getDscrRegistryType() == null ? other.getDscrRegistryType() == null : this.getDscrRegistryType().equals(other.getDscrRegistryType()))
            && (this.getDscrRegistryConfig() == null ? other.getDscrRegistryConfig() == null : this.getDscrRegistryConfig().equals(other.getDscrRegistryConfig()))
            && (this.getIsDelete() == null ? other.getIsDelete() == null : this.getIsDelete().equals(other.getIsDelete()))
            && (this.getGmtCreate() == null ? other.getGmtCreate() == null : this.getGmtCreate().equals(other.getGmtCreate()))
            && (this.getGmtModified() == null ? other.getGmtModified() == null : this.getGmtModified().equals(other.getGmtModified()));
    }

    /**
     *
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getDscrRegistryId() == null) ? 0 : getDscrRegistryId().hashCode());
        result = prime * result + ((getDscrRegistryType() == null) ? 0 : getDscrRegistryType().hashCode());
        result = prime * result + ((getDscrRegistryConfig() == null) ? 0 : getDscrRegistryConfig().hashCode());
        result = prime * result + ((getIsDelete() == null) ? 0 : getIsDelete().hashCode());
        result = prime * result + ((getGmtCreate() == null) ? 0 : getGmtCreate().hashCode());
        result = prime * result + ((getGmtModified() == null) ? 0 : getGmtModified().hashCode());
        return result;
    }
}