package com.doctorwork.sword.gateway.dal.model;

import java.io.Serializable;
import java.util.Date;

/**
 * This class corresponds to the database table <tt>server_info</tt>
 * 
 * This file is generated by <tt>dwframe<tt>
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may be
 * OVERWRITTEN by someone else. To modify the file, you should go to find the file
 * <tt>{project-home}/dalgen/mybatis_generator.xml<tt>. Modify the configuration file
 * according to your needs, then run <tt>ant</tt> to generate this file in {project-home}/dalgen.
 * 
 * @author dwframe
 * @since 2019-06-22
 */
public class ServerInfo implements Serializable {
    /**
     * <pre>
     * 
     * This field corresponds to the database column <tt>server_info.id<tt>
     * </pre>
     */
    private Long id;

    /**
     * <pre>
     * 服务IP
     * This field corresponds to the database column <tt>server_info.srv_ip<tt>
     * </pre>
     */
    private String srvIp;

    /**
     * <pre>
     * 服务端口
     * This field corresponds to the database column <tt>server_info.srv_port<tt>
     * </pre>
     */
    private Integer srvPort;

    /**
     * <pre>
     * 服务名称
     * This field corresponds to the database column <tt>server_info.srv_name<tt>
     * </pre>
     */
    private String srvName;

    /**
     * <pre>
     * apollo对应的appId
     * This field corresponds to the database column <tt>server_info.apollo_id<tt>
     * </pre>
     */
    private String apolloId;

    /**
     * <pre>
     * 服务信息备注
     * This field corresponds to the database column <tt>server_info.srv_comment<tt>
     * </pre>
     */
    private String srvComment;

    /**
     * <pre>
     * 是否删除，0-未删除，1-删除，默认为0
     * This field corresponds to the database column <tt>server_info.is_delete<tt>
     * </pre>
     */
    private Integer isDelete;

    /**
     * <pre>
     * Create time, common column by DB rules
     * This field corresponds to the database column <tt>server_info.gmt_create<tt>
     * </pre>
     */
    private Date gmtCreate;

    /**
     * <pre>
     * Modified time,common column by DB rules 
     * This field corresponds to the database column <tt>server_info.gmt_modified<tt>
     * </pre>
     */
    private Date gmtModified;

    /** serialVersionUID */
    private static final long serialVersionUID = 1L;

    /**
     * <pre>
     * This field corresponds to the database column <tt>server_info.id<tt>
     * </pre>
     *
     * @return 
     */
    public Long getId() {
        return id;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>server_info.id<tt>
     * </pre>
     *
     * @param id 
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>server_info.srv_ip<tt>
     * </pre>
     *
     * @return 服务IP
     */
    public String getSrvIp() {
        return srvIp;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>server_info.srv_ip<tt>
     * </pre>
     *
     * @param srvIp 服务IP
     */
    public void setSrvIp(String srvIp) {
        this.srvIp = srvIp == null ? null : srvIp.trim();
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>server_info.srv_port<tt>
     * </pre>
     *
     * @return 服务端口
     */
    public Integer getSrvPort() {
        return srvPort;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>server_info.srv_port<tt>
     * </pre>
     *
     * @param srvPort 服务端口
     */
    public void setSrvPort(Integer srvPort) {
        this.srvPort = srvPort;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>server_info.srv_name<tt>
     * </pre>
     *
     * @return 服务名称
     */
    public String getSrvName() {
        return srvName;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>server_info.srv_name<tt>
     * </pre>
     *
     * @param srvName 服务名称
     */
    public void setSrvName(String srvName) {
        this.srvName = srvName == null ? null : srvName.trim();
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>server_info.apollo_id<tt>
     * </pre>
     *
     * @return apollo对应的appId
     */
    public String getApolloId() {
        return apolloId;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>server_info.apollo_id<tt>
     * </pre>
     *
     * @param apolloId apollo对应的appId
     */
    public void setApolloId(String apolloId) {
        this.apolloId = apolloId == null ? null : apolloId.trim();
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>server_info.srv_comment<tt>
     * </pre>
     *
     * @return 服务信息备注
     */
    public String getSrvComment() {
        return srvComment;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>server_info.srv_comment<tt>
     * </pre>
     *
     * @param srvComment 服务信息备注
     */
    public void setSrvComment(String srvComment) {
        this.srvComment = srvComment == null ? null : srvComment.trim();
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>server_info.is_delete<tt>
     * </pre>
     *
     * @return 是否删除，0-未删除，1-删除，默认为0
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>server_info.is_delete<tt>
     * </pre>
     *
     * @param isDelete 是否删除，0-未删除，1-删除，默认为0
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>server_info.gmt_create<tt>
     * </pre>
     *
     * @return Create time, common column by DB rules
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>server_info.gmt_create<tt>
     * </pre>
     *
     * @param gmtCreate Create time, common column by DB rules
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>server_info.gmt_modified<tt>
     * </pre>
     *
     * @return Modified time,common column by DB rules 
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>server_info.gmt_modified<tt>
     * </pre>
     *
     * @param gmtModified Modified time,common column by DB rules 
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", srvIp=").append(srvIp);
        sb.append(", srvPort=").append(srvPort);
        sb.append(", srvName=").append(srvName);
        sb.append(", apolloId=").append(apolloId);
        sb.append(", srvComment=").append(srvComment);
        sb.append(", isDelete=").append(isDelete);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append("]");
        return sb.toString();
    }

    /**
     *
     * @param that
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ServerInfo other = (ServerInfo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getSrvIp() == null ? other.getSrvIp() == null : this.getSrvIp().equals(other.getSrvIp()))
            && (this.getSrvPort() == null ? other.getSrvPort() == null : this.getSrvPort().equals(other.getSrvPort()))
            && (this.getSrvName() == null ? other.getSrvName() == null : this.getSrvName().equals(other.getSrvName()))
            && (this.getApolloId() == null ? other.getApolloId() == null : this.getApolloId().equals(other.getApolloId()))
            && (this.getSrvComment() == null ? other.getSrvComment() == null : this.getSrvComment().equals(other.getSrvComment()))
            && (this.getIsDelete() == null ? other.getIsDelete() == null : this.getIsDelete().equals(other.getIsDelete()))
            && (this.getGmtCreate() == null ? other.getGmtCreate() == null : this.getGmtCreate().equals(other.getGmtCreate()))
            && (this.getGmtModified() == null ? other.getGmtModified() == null : this.getGmtModified().equals(other.getGmtModified()));
    }

    /**
     *
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getSrvIp() == null) ? 0 : getSrvIp().hashCode());
        result = prime * result + ((getSrvPort() == null) ? 0 : getSrvPort().hashCode());
        result = prime * result + ((getSrvName() == null) ? 0 : getSrvName().hashCode());
        result = prime * result + ((getApolloId() == null) ? 0 : getApolloId().hashCode());
        result = prime * result + ((getSrvComment() == null) ? 0 : getSrvComment().hashCode());
        result = prime * result + ((getIsDelete() == null) ? 0 : getIsDelete().hashCode());
        result = prime * result + ((getGmtCreate() == null) ? 0 : getGmtCreate().hashCode());
        result = prime * result + ((getGmtModified() == null) ? 0 : getGmtModified().hashCode());
        return result;
    }
}