package com.doctorwork.sword.gateway.admin.dal.model;

import java.io.Serializable;
import java.util.Date;

/**
 * This class corresponds to the database table <tt>discover_config</tt>
 * 
 * This file is generated by <tt>dwframe<tt>
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may be
 * OVERWRITTEN by someone else. To modify the file, you should go to find the file
 * <tt>{project-home}/dalgen/mybatis_generator.xml<tt>. Modify the configuration file
 * according to your needs, then run <tt>ant</tt> to generate this file in {project-home}/dalgen.
 * 
 * @author dwframe
 * @since 2019-07-12
 */
public class DiscoverConfig implements Serializable {
    /**
     * <pre>
     * 
     * This field corresponds to the database column <tt>discover_config.id<tt>
     * </pre>
     */
    private Long id;

    /**
     * <pre>
     * 服务发现配置
     * This field corresponds to the database column <tt>discover_config.dscr_id<tt>
     * </pre>
     */
    private String dscrId;

    /**
     * <pre>
     * 服务发现类型
     * This field corresponds to the database column <tt>discover_config.dscr_type<tt>
     * </pre>
     */
    private String dscrType;

    /**
     * <pre>
     * 服务发现配置
     * This field corresponds to the database column <tt>discover_config.dscr_config<tt>
     * </pre>
     */
    private String dscrConfig;

    /**
     * <pre>
     * 注册中心配置标识
     * This field corresponds to the database column <tt>discover_config.dscr_regitry_id<tt>
     * </pre>
     */
    private String dscrRegitryId;

    /**
     * <pre>
     * 是否启用预加载 0默认启用 1不启动
     * This field corresponds to the database column <tt>discover_config.dscr_preload_enable<tt>
     * </pre>
     */
    private Integer dscrPreloadEnable;

    /**
     * <pre>
     * 是否删除，0-未删除，1-删除，默认为0
     * This field corresponds to the database column <tt>discover_config.is_delete<tt>
     * </pre>
     */
    private Integer isDelete;

    /**
     * <pre>
     * Create time, common column by DB rules
     * This field corresponds to the database column <tt>discover_config.gmt_create<tt>
     * </pre>
     */
    private Date gmtCreate;

    /**
     * <pre>
     * Modified time,common column by DB rules 
     * This field corresponds to the database column <tt>discover_config.gmt_modified<tt>
     * </pre>
     */
    private Date gmtModified;

    /** serialVersionUID */
    private static final long serialVersionUID = 1L;

    /**
     * <pre>
     * This field corresponds to the database column <tt>discover_config.id<tt>
     * </pre>
     *
     * @return 
     */
    public Long getId() {
        return id;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>discover_config.id<tt>
     * </pre>
     *
     * @param id 
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>discover_config.dscr_id<tt>
     * </pre>
     *
     * @return 服务发现配置
     */
    public String getDscrId() {
        return dscrId;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>discover_config.dscr_id<tt>
     * </pre>
     *
     * @param dscrId 服务发现配置
     */
    public void setDscrId(String dscrId) {
        this.dscrId = dscrId == null ? null : dscrId.trim();
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>discover_config.dscr_type<tt>
     * </pre>
     *
     * @return 服务发现类型
     */
    public String getDscrType() {
        return dscrType;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>discover_config.dscr_type<tt>
     * </pre>
     *
     * @param dscrType 服务发现类型
     */
    public void setDscrType(String dscrType) {
        this.dscrType = dscrType == null ? null : dscrType.trim();
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>discover_config.dscr_config<tt>
     * </pre>
     *
     * @return 服务发现配置
     */
    public String getDscrConfig() {
        return dscrConfig;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>discover_config.dscr_config<tt>
     * </pre>
     *
     * @param dscrConfig 服务发现配置
     */
    public void setDscrConfig(String dscrConfig) {
        this.dscrConfig = dscrConfig == null ? null : dscrConfig.trim();
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>discover_config.dscr_regitry_id<tt>
     * </pre>
     *
     * @return 注册中心配置标识
     */
    public String getDscrRegitryId() {
        return dscrRegitryId;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>discover_config.dscr_regitry_id<tt>
     * </pre>
     *
     * @param dscrRegitryId 注册中心配置标识
     */
    public void setDscrRegitryId(String dscrRegitryId) {
        this.dscrRegitryId = dscrRegitryId == null ? null : dscrRegitryId.trim();
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>discover_config.dscr_preload_enable<tt>
     * </pre>
     *
     * @return 是否启用预加载 0默认启用 1不启动
     */
    public Integer getDscrPreloadEnable() {
        return dscrPreloadEnable;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>discover_config.dscr_preload_enable<tt>
     * </pre>
     *
     * @param dscrPreloadEnable 是否启用预加载 0默认启用 1不启动
     */
    public void setDscrPreloadEnable(Integer dscrPreloadEnable) {
        this.dscrPreloadEnable = dscrPreloadEnable;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>discover_config.is_delete<tt>
     * </pre>
     *
     * @return 是否删除，0-未删除，1-删除，默认为0
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>discover_config.is_delete<tt>
     * </pre>
     *
     * @param isDelete 是否删除，0-未删除，1-删除，默认为0
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>discover_config.gmt_create<tt>
     * </pre>
     *
     * @return Create time, common column by DB rules
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>discover_config.gmt_create<tt>
     * </pre>
     *
     * @param gmtCreate Create time, common column by DB rules
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>discover_config.gmt_modified<tt>
     * </pre>
     *
     * @return Modified time,common column by DB rules 
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>discover_config.gmt_modified<tt>
     * </pre>
     *
     * @param gmtModified Modified time,common column by DB rules 
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", dscrId=").append(dscrId);
        sb.append(", dscrType=").append(dscrType);
        sb.append(", dscrConfig=").append(dscrConfig);
        sb.append(", dscrRegitryId=").append(dscrRegitryId);
        sb.append(", dscrPreloadEnable=").append(dscrPreloadEnable);
        sb.append(", isDelete=").append(isDelete);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append("]");
        return sb.toString();
    }

    /**
     *
     * @param that
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DiscoverConfig other = (DiscoverConfig) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getDscrId() == null ? other.getDscrId() == null : this.getDscrId().equals(other.getDscrId()))
            && (this.getDscrType() == null ? other.getDscrType() == null : this.getDscrType().equals(other.getDscrType()))
            && (this.getDscrConfig() == null ? other.getDscrConfig() == null : this.getDscrConfig().equals(other.getDscrConfig()))
            && (this.getDscrRegitryId() == null ? other.getDscrRegitryId() == null : this.getDscrRegitryId().equals(other.getDscrRegitryId()))
            && (this.getDscrPreloadEnable() == null ? other.getDscrPreloadEnable() == null : this.getDscrPreloadEnable().equals(other.getDscrPreloadEnable()))
            && (this.getIsDelete() == null ? other.getIsDelete() == null : this.getIsDelete().equals(other.getIsDelete()))
            && (this.getGmtCreate() == null ? other.getGmtCreate() == null : this.getGmtCreate().equals(other.getGmtCreate()))
            && (this.getGmtModified() == null ? other.getGmtModified() == null : this.getGmtModified().equals(other.getGmtModified()));
    }

    /**
     *
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getDscrId() == null) ? 0 : getDscrId().hashCode());
        result = prime * result + ((getDscrType() == null) ? 0 : getDscrType().hashCode());
        result = prime * result + ((getDscrConfig() == null) ? 0 : getDscrConfig().hashCode());
        result = prime * result + ((getDscrRegitryId() == null) ? 0 : getDscrRegitryId().hashCode());
        result = prime * result + ((getDscrPreloadEnable() == null) ? 0 : getDscrPreloadEnable().hashCode());
        result = prime * result + ((getIsDelete() == null) ? 0 : getIsDelete().hashCode());
        result = prime * result + ((getGmtCreate() == null) ? 0 : getGmtCreate().hashCode());
        result = prime * result + ((getGmtModified() == null) ? 0 : getGmtModified().hashCode());
        return result;
    }
}