package com.doctorwork.sword.gateway.admin.dal.model;

import java.io.Serializable;
import java.util.Date;

/**
 * This class corresponds to the database table <tt>route_predicate</tt>
 * 
 * This file is generated by <tt>dwframe<tt>
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may be
 * OVERWRITTEN by someone else. To modify the file, you should go to find the file
 * <tt>{project-home}/dalgen/mybatis_generator.xml<tt>. Modify the configuration file
 * according to your needs, then run <tt>ant</tt> to generate this file in {project-home}/dalgen.
 * 
 * @author dwframe
 * @since 2019-07-28
 */
public class RoutePredicate implements Serializable {
    /**
     * <pre>
     * 
     * This field corresponds to the database column <tt>route_predicate.id<tt>
     * </pre>
     */
    private Long id;

    /**
     * <pre>
     * 路由ID
     * This field corresponds to the database column <tt>route_predicate.route_id<tt>
     * </pre>
     */
    private Long routeId;

    /**
     * <pre>
     * 路由谓词信息
     * This field corresponds to the database column <tt>route_predicate.route_predicate_key<tt>
     * </pre>
     */
    private String routePredicateKey;

    /**
     * <pre>
     * 路由谓词信息
     * This field corresponds to the database column <tt>route_predicate.route_predicate_value<tt>
     * </pre>
     */
    private String routePredicateValue;

    /**
     * <pre>
     * 路由谓词规则说明
     * This field corresponds to the database column <tt>route_predicate.route_predicate_comment<tt>
     * </pre>
     */
    private String routePredicateComment;

    /**
     * <pre>
     * 是否删除，0-未删除，1-删除，默认为0
     * This field corresponds to the database column <tt>route_predicate.is_delete<tt>
     * </pre>
     */
    private Integer isDelete;

    /**
     * <pre>
     * Create time, common column by DB rules
     * This field corresponds to the database column <tt>route_predicate.gmt_create<tt>
     * </pre>
     */
    private Date gmtCreate;

    /**
     * <pre>
     * Modified time,common column by DB rules 
     * This field corresponds to the database column <tt>route_predicate.gmt_modified<tt>
     * </pre>
     */
    private Date gmtModified;

    /** serialVersionUID */
    private static final long serialVersionUID = 1L;

    /**
     * <pre>
     * This field corresponds to the database column <tt>route_predicate.id<tt>
     * </pre>
     *
     * @return 
     */
    public Long getId() {
        return id;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>route_predicate.id<tt>
     * </pre>
     *
     * @param id 
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>route_predicate.route_id<tt>
     * </pre>
     *
     * @return 路由ID
     */
    public Long getRouteId() {
        return routeId;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>route_predicate.route_id<tt>
     * </pre>
     *
     * @param routeId 路由ID
     */
    public void setRouteId(Long routeId) {
        this.routeId = routeId;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>route_predicate.route_predicate_key<tt>
     * </pre>
     *
     * @return 路由谓词信息
     */
    public String getRoutePredicateKey() {
        return routePredicateKey;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>route_predicate.route_predicate_key<tt>
     * </pre>
     *
     * @param routePredicateKey 路由谓词信息
     */
    public void setRoutePredicateKey(String routePredicateKey) {
        this.routePredicateKey = routePredicateKey == null ? null : routePredicateKey.trim();
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>route_predicate.route_predicate_value<tt>
     * </pre>
     *
     * @return 路由谓词信息
     */
    public String getRoutePredicateValue() {
        return routePredicateValue;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>route_predicate.route_predicate_value<tt>
     * </pre>
     *
     * @param routePredicateValue 路由谓词信息
     */
    public void setRoutePredicateValue(String routePredicateValue) {
        this.routePredicateValue = routePredicateValue == null ? null : routePredicateValue.trim();
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>route_predicate.route_predicate_comment<tt>
     * </pre>
     *
     * @return 路由谓词规则说明
     */
    public String getRoutePredicateComment() {
        return routePredicateComment;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>route_predicate.route_predicate_comment<tt>
     * </pre>
     *
     * @param routePredicateComment 路由谓词规则说明
     */
    public void setRoutePredicateComment(String routePredicateComment) {
        this.routePredicateComment = routePredicateComment == null ? null : routePredicateComment.trim();
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>route_predicate.is_delete<tt>
     * </pre>
     *
     * @return 是否删除，0-未删除，1-删除，默认为0
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>route_predicate.is_delete<tt>
     * </pre>
     *
     * @param isDelete 是否删除，0-未删除，1-删除，默认为0
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>route_predicate.gmt_create<tt>
     * </pre>
     *
     * @return Create time, common column by DB rules
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>route_predicate.gmt_create<tt>
     * </pre>
     *
     * @param gmtCreate Create time, common column by DB rules
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>route_predicate.gmt_modified<tt>
     * </pre>
     *
     * @return Modified time,common column by DB rules 
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>route_predicate.gmt_modified<tt>
     * </pre>
     *
     * @param gmtModified Modified time,common column by DB rules 
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", routeId=").append(routeId);
        sb.append(", routePredicateKey=").append(routePredicateKey);
        sb.append(", routePredicateValue=").append(routePredicateValue);
        sb.append(", routePredicateComment=").append(routePredicateComment);
        sb.append(", isDelete=").append(isDelete);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append("]");
        return sb.toString();
    }

    /**
     *
     * @param that
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        RoutePredicate other = (RoutePredicate) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getRouteId() == null ? other.getRouteId() == null : this.getRouteId().equals(other.getRouteId()))
            && (this.getRoutePredicateKey() == null ? other.getRoutePredicateKey() == null : this.getRoutePredicateKey().equals(other.getRoutePredicateKey()))
            && (this.getRoutePredicateValue() == null ? other.getRoutePredicateValue() == null : this.getRoutePredicateValue().equals(other.getRoutePredicateValue()))
            && (this.getRoutePredicateComment() == null ? other.getRoutePredicateComment() == null : this.getRoutePredicateComment().equals(other.getRoutePredicateComment()))
            && (this.getIsDelete() == null ? other.getIsDelete() == null : this.getIsDelete().equals(other.getIsDelete()))
            && (this.getGmtCreate() == null ? other.getGmtCreate() == null : this.getGmtCreate().equals(other.getGmtCreate()))
            && (this.getGmtModified() == null ? other.getGmtModified() == null : this.getGmtModified().equals(other.getGmtModified()));
    }

    /**
     *
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getRouteId() == null) ? 0 : getRouteId().hashCode());
        result = prime * result + ((getRoutePredicateKey() == null) ? 0 : getRoutePredicateKey().hashCode());
        result = prime * result + ((getRoutePredicateValue() == null) ? 0 : getRoutePredicateValue().hashCode());
        result = prime * result + ((getRoutePredicateComment() == null) ? 0 : getRoutePredicateComment().hashCode());
        result = prime * result + ((getIsDelete() == null) ? 0 : getIsDelete().hashCode());
        result = prime * result + ((getGmtCreate() == null) ? 0 : getGmtCreate().hashCode());
        result = prime * result + ((getGmtModified() == null) ? 0 : getGmtModified().hashCode());
        return result;
    }
}